---
resources:
    - name: stemmarest-sources
      type: git
      source:
        uri: {{stemmarest-sources-uri}}
        branch: {{stemmarest-sources-branch}}
        paths: [stemmarest, ci/resources]

    - name: stemmarest-image
      type: docker-image
      source:
        repository: {{stemmarest-final-image}}
        insecure_registries: [ {{insecure-registries}} ]

    - name: maven-config
      type: git
      source:
        uri: {{maven-config-uri}}
        private_key: {{DHUniWienMU-priv-key}}

    - name: stemmarest-config
      type: git
      source:
        uri: {{stemmarest-config-uri}}
        private_key: {{DHUniWienMU-priv-key}}

    - name: version
      type: semver
      source:
        driver: git
        uri: {{version-uri}}
        private_key: {{DHUniWienMU-priv-key}}
        branch: {{version-branch}}
        file: {{version-file}}
        initial_version: "0.0.0"

    - name: ssh-keys
      type: git
      source:
        uri: {{ssh-keys-uri}}
        private_key: {{DHUniWienMU-priv-key}}

    - name: ci
      type: git
      source:
        uri: {{ci-uri}}


jobs:

  - name: test
    plan:
      - aggregate:
        - get: stemmarest-sources
          trigger: true
        - get: maven-config
          trigger: true

      - task: task-test

        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: {{stemmarest-test-image}}
              insecure_registries: [ {{insecure-registries}} ]

          inputs:
            - name: stemmarest-sources
            - name: maven-config

          run:
            path: sh
            args:
              - -exc
              - |
                mkdir -p /root/.m2/
                cp maven-config/settings.xml /root/.m2/
                cd stemmarest-sources/stemmarest/
                mvn --batch-mode --quiet test
            params:
              MAVEN_OPTS: {{maven-opts}}

  - name: package
    plan:
      - aggregate:
        - get: stemmarest-sources
          trigger: true
          passed: [test]
        - get: maven-config
          trigger: true

      - put: version
        params:
          bump: patch

      - task: task-package

        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: {{stemmarest-test-image}}
              insecure_registries: [ {{insecure-registries}} ]

          inputs:
            - name: stemmarest-sources
            - name: maven-config
          outputs:
            - name: artifacts

          run:
            params:
              MAVEN_OPTS: {{maven-opts}}
            path: sh
            args:
            - -exc
            - |
              # fetch settings.xml
              #
              mkdir -p /root/.m2/
              cp maven-config/settings.xml /root/.m2/
              cd stemmarest-sources/stemmarest/
              # run maven
              #
              /usr/bin/mvn package
              # copy results to output
              #
              /bin/cp target/stemmarest.war ../../artifacts/
              /bin/cp build/server.xml ../../artifacts/
              /bin/cp build/tomcat-users.xml ../../artifacts/
              # set initial random password
              /bin/sed -i s/CHANGE_THIS/`/usr/bin/pwgen 16`/ ../../artifacts/tomcat-users.xml
              # also get Dockerfile for put: below
              /bin/cp ../ci/resources/Dockerfile-stemmarest-final ../../artifacts/Dockerfile

      # build docker image
      - put: stemmarest-image
        params:
          # The path of a directory containing a Dockerfile to build.
          build: artifacts/
          tag: version/version
          tag_as_latest: True


  - name: deploy-editions-moe-test
    plan:
      - aggregate:
        - get: stemmarest-image
          passed: [package]
          trigger: true
        - get: stemmarest-config
        - get: ssh-keys
        - get: ci
        - get: version

      - task: deploy-editions-moe-test

        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: {{stemmarest-test-image}}
              insecure_registries: [ {{insecure-registries}} ]

          inputs:
            - name: ci
            - name: version
            - name: stemmarest-config
            - name: ssh-keys

          run:
            path: sh
            args:
              - "ci/bin/deploy.sh"
              - "stemmarest-config/deploy-editions-moe-test.conf"


  - name: deploy-editions-moe
    plan:
      - aggregate:
        - get: stemmarest-image
          passed: [package]
        - get: stemmarest-config
        - get: ssh-keys
        - get: ci
        - get: version

      - task: deploy-editions-moe

        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: {{stemmarest-test-image}}
              insecure_registries: [ {{insecure-registries}} ]

          inputs:
            - name: ci
            - name: version
            - name: stemmarest-config
            - name: ssh-keys

          run:
            path: sh
            args:
              - "ci/bin/deploy.sh"
              - "stemmarest-config/deploy-editions-moe.conf"
